name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - run: mvn --no-transfer-progress verify source:jar javadoc:jar

      - run: mvn --no-transfer-progress deploy --settings=".github/workflows/settings.xml" -Dmaven.test.skip=true
        if: ${{ github.ref == 'refs/heads/master' && github.repository == 'square/javapoet' }}
